version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
    postgres:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
